import { Location } from "@/payload-types"
import { local } from "@/repository"

export const brazilianLocationsData: Omit<Location, "id" | "updatedAt" | "createdAt">[] = [
  {
    zip: "01414-001",
    city: "São Paulo - Jardins",
    state_abbr: "SP",
    state_name: "São Paulo",
    county: "Zona Sul",
    latitude: -23.56,
    longitude: -46.66,
    est_population: 95000,
  },
  {
    zip: "04515-030",
    city: "São Paulo - Moema",
    state_abbr: "SP",
    state_name: "São Paulo",
    county: "Zona Sul",
    latitude: -23.60,
    longitude: -46.66,
    est_population: 85000,
  },
  {
    zip: "04538-133",
    city: "São Paulo - Itaim Bibi",
    state_abbr: "SP",
    state_name: "São Paulo",
    county: "Zona Sul",
    latitude: -23.58,
    longitude: -46.68,
    est_population: 78000,
  },
  {
    zip: "05422-001",
    city: "São Paulo - Pinheiros",
    state_abbr: "SP",
    state_name: "São Paulo",
    county: "Zona Oeste",
    latitude: -23.56,
    longitude: -46.69,
    est_population: 68000,
  },
  {
    zip: "05435-000",
    city: "São Paulo - Vila Madalena",
    state_abbr: "SP",
    state_name: "São Paulo",
    county: "Zona Oeste",
    latitude: -23.55,
    longitude: -46.69,
    est_population: 50000,
  },
  {
    zip: "06454-000",
    city: "Barueri - Alphaville",
    state_abbr: "SP",
    state_name: "São Paulo",
    county: "Grande São Paulo",
    latitude: -23.49,
    longitude: -46.85,
    est_population: 40000,
  },
  {
    zip: "22440-032",
    city: "Rio de Janeiro - Leblon",
    state_abbr: "RJ",
    state_name: "Rio de Janeiro",
    county: "Zona Sul",
    latitude: -22.98,
    longitude: -43.22,
    est_population: 45000,
  },
  {
    zip: "22410-002",
    city: "Rio de Janeiro - Ipanema",
    state_abbr: "RJ",
    state_name: "Rio de Janeiro",
    county: "Zona Sul",
    latitude: -22.98,
    longitude: -43.20,
    est_population: 42000,
  },
  {
    zip: "22640-100",
    city: "Rio de Janeiro - Barra da Tijuca",
    state_abbr: "RJ",
    state_name: "Rio de Janeiro",
    county: "Zona Oeste",
    latitude: -23.00,
    longitude: -43.36,
    est_population: 135000,
  },
  {
    zip: "80420-000",
    city: "Curitiba - Batel",
    state_abbr: "PR",
    state_name: "Paraná",
    county: "Central",
    latitude: -25.44,
    longitude: -49.28,
    est_population: 35000,
  },
  {
    zip: "81200-100",
    city: "Curitiba - Ecoville",
    state_abbr: "PR",
    state_name: "Paraná",
    county: "Mossunguê",
    latitude: -25.43,
    longitude: -49.33,
    est_population: 28000,
  },
  {
    zip: "88053-300",
    city: "Florianópolis - Jurerê Internacional",
    state_abbr: "SC",
    state_name: "Santa Catarina",
    county: "Norte da Ilha",
    latitude: -27.43,
    longitude: -48.49,
    est_population: 20000,
  },
  {
    zip: "88063-000",
    city: "Florianópolis - Campeche",
    state_abbr: "SC",
    state_name: "Santa Catarina",
    county: "Sul da Ilha",
    latitude: -27.68,
    longitude: -48.49,
    est_population: 32000,
  },
  {
    zip: "88330-000",
    city: "Balneário Camboriú - Barra Sul",
    state_abbr: "SC",
    state_name: "Santa Catarina",
    county: "Litoral Norte",
    latitude: -26.99,
    longitude: -48.63,
    est_population: 45000,
  },
  {
    zip: "30130-100",
    city: "Belo Horizonte - Savassi",
    state_abbr: "MG",
    state_name: "Minas Gerais",
    county: "Centro-Sul",
    latitude: -19.93,
    longitude: -43.93,
    est_population: 38000,
  },
  {
    zip: "70200-001",
    city: "Brasília - Asa Sul",
    state_abbr: "DF",
    state_name: "Distrito Federal",
    county: "Plano Piloto",
    latitude: -15.79,
    longitude: -47.88,
    est_population: 110000,
  },
]

export async function seedLocations(): Promise<void> {
  console.log(`Seeding ${brazilianLocationsData.length} Brazilian locations...`)
  for (const location of brazilianLocationsData) {
    await local.location.create(location)
  }
}
